// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#ifndef MONGOOSE_GLUE_H
#define MONGOOSE_GLUE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "mongoose.h"

#define WIZARD_ENABLE_HTTP 1
#define WIZARD_ENABLE_HTTPS 0
#define WIZARD_ENABLE_HTTP_UI 1
#define WIZARD_ENABLE_HTTP_UI_LOGIN 1

#define WIZARD_ENABLE_WEBSOCKET 1

#define WIZARD_ENABLE_MQTT 0
#define WIZARD_MQTT_URL ""

#define WIZARD_ENABLE_SNTP 0  // Enable time sync.
#define WIZARD_SNTP_TYPE 0    // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_SNTP_URL "udp://time.google.com:123"  // Custom SNTP server URL
#define WIZARD_SNTP_INTERVAL_SECONDS 3600            // Frequency of SNTP syncs

#define WIZARD_DNS_TYPE 0  // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_DNS_URL "udp://8.8.8.8:53"  // Custom DNS server URL
#define WIZARD_CAPTIVE_PORTAL 0
#define WIZARD_ENABLE_MDNS 0
#define WIZARD_MDNS_NAME ""

#define WIZARD_ENABLE_WIFI 0
#define WIZARD_WIFI_NAME "MyNet"
#define WIZARD_WIFI_PASS "MyPass"
#define WIZARD_ENABLE_WIFI_AP 0
#define WIZARD_WIFI_AP_NAME "MyAp"
#define WIZARD_WIFI_AP_PASS "MyApPass"

#define WIZARD_ENABLE_MODBUS 0
#define WIZARD_MODBUS_PORT 502

#ifndef WIZARD_REBOOT_TIMEOUT_MS
#define WIZARD_REBOOT_TIMEOUT_MS 500
#endif

void mongoose_init(void);    // Initialise Mongoose
void mongoose_poll(void);    // Poll Mongoose
extern struct mg_mgr g_mgr;  // Mongoose event manager

void mongoose_set_http_handlers(const char *name, ...);
void mongoose_add_ws_handler(unsigned ms, void (*)(struct mg_connection *));
void mongoose_add_ws_reporter(unsigned ms, const char *name);

struct mongoose_mqtt_handlers {
  struct mg_connection *(*connect_fn)(mg_event_handler_t);
  void (*on_connect_fn)(struct mg_connection *, int);
  void (*on_message_fn)(struct mg_connection *, struct mg_str, struct mg_str);
  void (*on_cmd_fn)(struct mg_connection *, struct mg_mqtt_message *);
};
void mongoose_set_mqtt_handlers(struct mongoose_mqtt_handlers *);

struct mongoose_modbus_handlers {
  bool (*read_reg_fn)(uint16_t address, uint16_t *value);
  bool (*write_reg_fn)(uint16_t address, uint16_t value);
};
void mongoose_set_modbus_handlers(struct mongoose_modbus_handlers *);

void mongoose_set_sntp_handler(void (*fn)(uint64_t epoch_ms));
void mongoose_set_sntp_server(const char *url);

void mongoose_set_auth_handler(int (*fn)(const char *user, const char *pass));

#if WIZARD_ENABLE_MQTT
void glue_lock_init(void);  // Initialise global Mongoose mutex
void glue_lock(void);       // Lock global Mongoose mutex
void glue_unlock(void);     // Unlock global Mongoose mutex
#else
#define glue_lock_init()
#define glue_lock()
#define glue_unlock()
#endif

// Update MDNS name. Works when MDNS is enabled.
void glue_mdns_update_name(const char *newname);

// Increment device change state counter - trigger UI refresh
void glue_update_state(void);

// Firmware Glue


int    glue_authenticate(const char *user, const char *pass);

struct nox {
  double nox_index;
};
void glue_get_nox(struct nox *);

struct pm {
  double mass_concentration_pm1p0;
};
void glue_get_pm(struct pm *);

struct co2 {
  double co2_concentration;
};
void glue_get_co2(struct co2 *);

struct voc {
  double voc_index;
};
void glue_get_voc(struct voc *);

struct humidity {
  double relative_humidity;
};
void glue_get_humidity(struct humidity *);

struct temperature {
  double temperature;
};
void glue_get_temperature(struct temperature *);

void glue_start_reboot(struct mg_str);  // Start an action
bool glue_check_reboot(void);  // Check if action is still in progress

void glue_start_reformat(struct mg_str);  // Start an action
bool glue_check_reformat(void);  // Check if action is still in progress

void glue_start_save_event(struct mg_str);  // Start an action
bool glue_check_save_event(void);  // Check if action is still in progress

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size);
bool glue_ota_end_firmware_update(void *context);
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len);

void *glue_upload_open_file_upload(char *file_name, size_t total_size);
bool glue_upload_close_file_upload(void *context);
bool glue_upload_write_file_upload(void *context, void *buf, size_t len);

struct state {
  int speed;
  int temperature;
  int humidity;
  int uptime;
  char version[20];
  bool online;
  bool lights;
  int level;
};
void glue_get_state(struct state *);

struct network_settings {
  char ip_address[20];
  char gw_address[20];
  char netmask[20];
  bool dhcp;
};
void glue_get_network_settings(struct network_settings *);
void glue_set_network_settings(struct network_settings *);

struct settings {
  char string_val[40];
  int log_level;
  double double_val;
  int int_val;
  bool bool_val;
};
void glue_get_settings(struct settings *);
void glue_set_settings(struct settings *);

struct security {
  char admin_password[40];
  char user_password[40];
};
void glue_get_security(struct security *);
void glue_set_security(struct security *);

struct events {
  int id;
  int timestamp;
  int priority;
  int status;
  char message[100];
};
bool glue_get_events(struct events *, size_t index);
void glue_set_events(struct events *, size_t index);




#ifdef __cplusplus
}
#endif
#endif  // MONGOOSE_GLUE_H
